In [28]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)


2.0.1


learnpytorch.io -> Online book for this.

### Introduction to Tensors

##### Creating Tensors

In [5]:
scalar = torch.tensor(7)
print(scalar, type(scalar))

tensor(7) <class 'torch.Tensor'>


In [6]:
scalar.ndim

0

In [7]:
# Gets tensor back as Python integer
scalar.item()

7

In [16]:
vector = torch.tensor([3, 5])
print(vector)
print("Shape -> ", vector.shape)
print("Size -> ", vector.size())
print("Dimension -> ", vector.ndim)

tensor([3, 5])
Shape ->  torch.Size([2])
Size ->  torch.Size([2])
Dimension ->  1


In [20]:
# MATRIX
MATRIX = torch.tensor([[6, 7, 8], 
                       [1, 2, 4]])
print(MATRIX.shape)
print(MATRIX.ndim)

torch.Size([2, 3])
2


In [26]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3, 5],
                        [3, 4, 5, 6],
                        [2, 8, 0, 7]]])
print(TENSOR.shape)
print("Dimension -> ", TENSOR.ndim)

torch.Size([1, 3, 4])
Dimension ->  3


##### Random Tensors

In [32]:
random_tensor = torch.rand(2, 3, 4)
print(random_tensor)

tensor([[[0.9636, 0.9434, 0.4521, 0.9219],
         [0.0318, 0.7505, 0.7100, 0.0490],
         [0.3333, 0.7297, 0.2864, 0.7014]],

        [[0.1299, 0.0306, 0.4254, 0.9555],
         [0.2009, 0.9239, 0.6654, 0.7598],
         [0.5344, 0.9752, 0.4501, 0.6182]]])


In [35]:
# Random tensor with simialar shape to an image tensor
random_image_tensor = torch.rand(size=(3, 220, 124)) # color channels, height, width
print(random_image_tensor)
random_tensor.shape, random_tensor.ndim

tensor([[[0.4713, 0.7790, 0.3908],
         [0.7141, 0.0171, 0.9815],
         [0.4586, 0.9415, 0.6688],
         ...,
         [0.5777, 0.2796, 0.5908],
         [0.3455, 0.8877, 0.6061],
         [0.1303, 0.4506, 0.6227]],

        [[0.3620, 0.8037, 0.8522],
         [0.8690, 0.2499, 0.0435],
         [0.0864, 0.0298, 0.2906],
         ...,
         [0.8739, 0.1624, 0.2695],
         [0.8901, 0.4293, 0.2110],
         [0.2846, 0.6306, 0.0349]],

        [[0.6036, 0.3497, 0.7769],
         [0.4484, 0.4092, 0.3366],
         [0.2407, 0.2987, 0.1763],
         ...,
         [0.5989, 0.3923, 0.9947],
         [0.1287, 0.4628, 0.9742],
         [0.4412, 0.6691, 0.1905]],

        ...,

        [[0.7740, 0.6091, 0.2976],
         [0.8313, 0.6197, 0.1946],
         [0.6551, 0.0138, 0.2221],
         ...,
         [0.0230, 0.9690, 0.8998],
         [0.4282, 0.8773, 0.3610],
         [0.1520, 0.9908, 0.7865]],

        [[0.0083, 0.8632, 0.8251],
         [0.8623, 0.4576, 0.3782],
         [0.

(torch.Size([2, 3, 4]), 'Dim -> ', 3)

##### Zeros and Ones

In [39]:
# Zeros
zeros = torch.zeros(size=(4, 7)) # Default dtype = float32
print(zeros)

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])


In [40]:
# Ones
ones = torch.ones(size=(6, 7)) # Default dtype = float32
print(ones)

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])


##### Range of Tensors and Tensors-like

In [44]:
one_to_ten = torch.arange(start=2, end=23)
print(one_to_ten)

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
        20, 21, 22])


In [46]:
tensors_like = torch.zeros_like(input=one_to_ten)
print(tensors_like)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


##### Tensor Matrix Multiplication

In [55]:
%%time

torch.matmul(one_to_ten, one_to_ten)

CPU times: user 107 µs, sys: 288 µs, total: 395 µs
Wall time: 308 µs


tensor(3794)

##### Finding max, min, mean, sum .. (Tensor Aggregation)

In [59]:
a = torch.arange(0, 100, 2)
torch.min(a), torch.max(a)

(tensor(0), tensor(98))

In [60]:
torch.mean(a)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [61]:
# Mean requires a float datatype to work!
a.type(torch.float32).mean()

tensor(49.)

In [62]:
# Finding sum
a.sum()

tensor(2450)

##### Finding index of the max and min value with argmax()

In [64]:
# Finding positional min and max
a.argmin(), a.argmax()

(tensor(0), tensor(49))

##### Reshaping, Viewing, Stacking, Squeezing, Unsqueezing, Permute

In [66]:
x = torch.arange(1., 10.)
x.shape

torch.Size([9])

In [67]:
torch.reshape(x, shape=(9, 1))

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [70]:
# View of a tensor shares the same memory with the original input
z = x.view(9, 1)
z
# Changing z changes x

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [74]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x, x], dim=1)
x_stacked

tensor([[1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8.],
        [9., 9., 9., 9., 9.]])

In [87]:
# Adds extra single dimensions to a tensor
x_unsqueezed = x_stacked.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[[1., 1., 1., 1., 1.],
          [2., 2., 2., 2., 2.],
          [3., 3., 3., 3., 3.],
          [4., 4., 4., 4., 4.],
          [5., 5., 5., 5., 5.],
          [6., 6., 6., 6., 6.],
          [7., 7., 7., 7., 7.],
          [8., 8., 8., 8., 8.],
          [9., 9., 9., 9., 9.]]]),
 torch.Size([1, 9, 5]))

In [79]:
# Remove extra single dimensions from a tensor
x_unsqueezed.squeeze()

tensor([[1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8.],
        [9., 9., 9., 9., 9.]])

In [95]:
# torch.permute -> rearranges the dimensions of a target tensor in a specified format
x_original = torch.rand(size=(3, 224, 215))
x_permuted = x_original.permute(2, 0, 1) # Shifts axis 0 -> 1, 1 -> 2, 2 -> 0
print("New shape: ", x_permuted.shape)
# Both x_original and x_permuted share the same memory!

New shape:  torch.Size([215, 3, 224])


### PyTorch tensors and NumPy

##### NumPy array to Tensor:

In [96]:
np_array = np.arange(1.0, 11.0)         # Default NumPy array -> float64
tensor = torch.from_numpy(np_array)     # Default PyTorch array -> float32
np_array, tensor
# np_array and tensor share different memories. Changing one doesnt affect the other.

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64))

##### Tensor array to NumPy

In [97]:
tensor = torch.ones(7)
np_array = tensor.numpy()
tensor, np_array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility

In [121]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A == random_tensor_B)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Checking GPU access for PyTorch
* Since NumPy needs cpu to work on, and GPU can be used for Tensors..

In [128]:
print(torch.version.hip)
print(torch.cuda.device_count())

None
0


In [129]:
tensor = torch.tensor([1, 2, 3])
tensor.device

device(type='cpu')

# DO Exercise