In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d = tf.constant(8)
print(tensor_zero_d)

tf.Tensor(8, shape=(), dtype=int32)


In [3]:
tensor_one_d = tf.constant([5, 7, -9.])
print(tensor_one_d)

tf.Tensor([ 5.  7. -9.], shape=(3,), dtype=float32)


In [4]:
tensor_two_d = tf.constant([
    [1, 2, 8],
    [5, 9, 0],
    [4, 6, 12],
    [43, 1, 0]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  8]
 [ 5  9  0]
 [ 4  6 12]
 [43  1  0]], shape=(4, 3), dtype=int32)


In [5]:
tensor_three_d = tf.constant([
        [
            [1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]
        ],

        [
            [13, 14, 15, 16],
            [17, 18, 19, 20],
            [21, 22, 23, 24]
        ]

])
print(tensor_three_d)
print("Dimension = ", tensor_three_d.ndim)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)
Dimension =  3


In [6]:
tensor_four_d = tf.constant([
    [
        [
            [1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]
        ],

        [
            [13, 14, 15, 16],
            [17, 18, 19, 20],
            [21, 22, 23, 24]
        ]

    ]
])
print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]], shape=(1, 2, 3, 4), dtype=int32)


In [7]:
# cast() -> zero for False and the other numbers True
tf.cast(tensor_one_d, dtype=tf.bool)

<tf.Tensor: shape=(3,), dtype=bool, numpy=array([ True,  True,  True])>

In [8]:
tensor_bool = tf.constant([True, False, True])
print(tensor_bool)

# Casting bool to int16
tf.cast(tensor_bool, dtype=tf.int16)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)


<tf.Tensor: shape=(3,), dtype=int16, numpy=array([1, 0, 1], dtype=int16)>

In [9]:
tensor_string = tf.constant(["hello World!", "How are you?"])
print(tensor_string)

tf.Tensor([b'hello World!' b'How are you?'], shape=(2,), dtype=string)


### Converting numpy_array to tensor

In [10]:
import numpy as np

In [11]:
np_array = np.array([1, 6, 21])

tensor_array = tf.convert_to_tensor(np_array)
print(tensor_array)

tf.Tensor([ 1  6 21], shape=(3,), dtype=int64)


### Identity Matrix in tensors

In [12]:
eye_tensor = tf.eye(
    num_rows=4,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.int16,
    )
print(eye_tensor)

# Experimenting with batch size
eye_tensor_batch_ = tf.eye(
    num_rows=4,
    num_columns=None,
    batch_shape=[3, 2],
    dtype=tf.dtypes.int16,
    )
print(eye_tensor_batch_)

tf.Tensor(
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]], shape=(4, 4), dtype=int16)
tf.Tensor(
[[[[1 0 0 0]
   [0 1 0 0]
   [0 0 1 0]
   [0 0 0 1]]

  [[1 0 0 0]
   [0 1 0 0]
   [0 0 1 0]
   [0 0 0 1]]]


 [[[1 0 0 0]
   [0 1 0 0]
   [0 0 1 0]
   [0 0 0 1]]

  [[1 0 0 0]
   [0 1 0 0]
   [0 0 1 0]
   [0 0 0 1]]]


 [[[1 0 0 0]
   [0 1 0 0]
   [0 0 1 0]
   [0 0 0 1]]

  [[1 0 0 0]
   [0 1 0 0]
   [0 0 1 0]
   [0 0 0 1]]]], shape=(3, 2, 4, 4), dtype=int16)


In [13]:
tf.fill([4, 2, 3], 6)

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[6, 6, 6],
        [6, 6, 6]],

       [[6, 6, 6],
        [6, 6, 6]],

       [[6, 6, 6],
        [6, 6, 6]],

       [[6, 6, 6],
        [6, 6, 6]]], dtype=int32)>

In [14]:
tf.ones(
    shape=[2, 5, 3],
    dtype=tf.dtypes.int16,
    name=None
)

<tf.Tensor: shape=(2, 5, 3), dtype=int16, numpy=
array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int16)>

In [15]:
tf.ones_like([
   [ 4, 5, 6],
   [3, 2, 1]
])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [20]:
random_tensor = tf.random.normal(
    [3, 4],
    mean=1.0,
    stddev=1.0,
    dtype=tf.float32,
    seed=None,
    name=None
)
random_tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.5690465 ,  0.41563433, -0.43171108,  0.6475992 ],
       [ 1.1889174 ,  0.74614024,  1.3675956 ,  1.1667556 ],
       [ 0.77167094,  2.4699678 ,  0.8085933 ,  2.1754217 ]],
      dtype=float32)>

In [23]:
uniform_tensor = tf.random.uniform(
    shape=[1, 3],
    dtype=tf.float32,
    minval=0,
    maxval=None, # Default is 1
    seed=None,
    name=None
)
print(uniform_tensor)

tf.Tensor([[0.20839238 0.0876174  0.7885964 ]], shape=(1, 3), dtype=float32)
